### ISSUE TITLE
Startup configuration and logging

### ISSUE THREAD

**Issue by DDonkov** [Bricknode/Bricknode.Soap.Sdk#6]
We have encountered the following error when following the startup config

"Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Bricknode.Soap.Sdk.Services.BfsLegalEntitiesService'."

We figured that we should further configure the following in Program.cs file → Create HostBuilder()

`            .ConfigureLogging(logging =>
            {
                logging.ClearProviders();
                logging.AddConsole();
            })`

**Comment by lindstromhenrik** [comment]
`ILogger` is not registered by default in ASP.NET Core (only the generic` ILogger<>`). In order to register the BfsApiClient using the `AddBfsApiClient(...)/AddMultiBfsApiClient(...)` extensions one have to also register a service for `ILogger`. The service can be resolved using the service provider using a common category name to `ILogger<>` (using the base class for all Bfs services here):

`services.AddSingleton<ILogger>((serviceProvider) => serviceProvider.GetService<ILogger<BfsServiceBase>>());`
